language: node_js
node_js:
  - "10.15.3"

cache: yarn

install:
  - yarn global add lerna jest
  - lerna bootstrap

matrix:
  include:
  - name: Client Pipeline
    env: PACKAGE_LOCATION=packages/client PACKAGE_NAME=@serge/client

script:
  - cd $PACKAGE_LOCATION
  - yarn test
  - yarn build


# deploy:
#   provider: script
#   script: now public --token $NOW_TOKEN
#   skip_cleanup: true
#   app: $PACKAGE_NAME