# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: PR

on:

  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
  
    name: Build/Test validation
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Setup repo
        uses: actions/checkout@v1

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name : Running dependency installation
        run: yarn install
        
      - name : Running project building
        run: yarn build
        
      - name : Running unit testing
        run: yarn test-unit

      - name : Build executable files
        run: yarn pkg-build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Attach Executable Files
          path: |
            /home/runner/work/serge/serge/packages/executable/builds/*_linux.zip
            /home/runner/work/serge/serge/packages/executable/builds/*_macos.zip
            /home/runner/work/serge/serge/packages/executable/builds/*_win64.zip
          if-no-files-found: error
